### ISSUE TITLE
GITCLONE via SSH within a container, using ahn SSH key pair

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [willhallonline/docker-ansible#23] opened 2020-03-05 13:16 UTC
hi again @willhallonline , 
* As mentioned earlier, I am currently using your `willhallonline/ansible:2.8-centos` image
* I am not sure it is due to your image design, or related to the underlying centos, or my simple wide ignorance, but I tested and re-tested a couple dozen of times, until I made it sure  : 
  * what I wanted to do , is to git clone my `ansible` playbook, into the container, to execute it.
  * I have an ssh key pair, inside a folder, of path `/path/to/my/secrets/.ssh`, where `/path/` is a folder that does not exist in the `centos` filesystem layout. So I just create it, and put away my keypair into it. 
  * I use the `GIT_SSH_COMMAND` to specify to git clone command, where the private key is. `export GIT_SSH_COMMAND='ssh -i /path/to/my/secrets/.ssh/my_private_key_file'`.
  * And here is what I made sure : 
    * unless `export GIT_SSH_COMMAND='ssh -i~/.ssh/id_rsa'`, 
    * `ssh -Tvvvai /path/to/my/secrets/.ssh/my_private_key_file  git@gitlab.com` always succeeds (no SSH problem)
    * `git clone $SSH_URI_TO_MY_REPO` will always fail 'permission denied', 
    * and the `git clone` still fails even if I : 

```bash
chmod 700 -R /path/to/my/secrets/.ssh
chmod 644 -R /path/to/my/secrets/.ssh/my_public_key_file.pub
chmod 600 -R /path/to/my/secrets/.ssh/my_private_key_file
```

Don't hesitate asking me any additional infos,

And thank you for your work.

ps: worth mentioning, I don't use at all this repo, I just docker pull `willhallonline/ansible:2.8-centos`, and build my own image, FROM yours.

**Comment by willhallonline** [comment] 2020-08-14 10:16
Hey @Jean-Baptiste-Lasselle , thanks for the great write up of your issue. I think that I understand the issue, however, I am not sure that I can help too much as I haven't really used this in a similar way. I will leave this issue open for the future to see whether I can fix it or do some testing.

**Comment by willhallonline** [comment] 2021-05-25 08:44
I am going to close this, not sure what I can do and I can't reproduce bug.

**Closed by willhallonline** 2021-05-25 08:44 UTC
